### ISSUE TITLE
timezone and Lastsync

### ISSUE THREAD

**Issue by sorentorp** [NoSubstitute/CB_QueryDetails#1]
Hi Kim

Line 12 in findCBDetailsSerial.gs doesn't take the local timezone into consideration. Can you fix this? I'll trade with a fix for your colors :-D

**Comment by NoSubstitute** [comment]
Done! :-)

You may have to change language and formating to fit your needs, but I think formating is the same for se and dk?

**Comment by sorentorp** [comment]
Perfekt! Thank you, works fine.
